"""baseline existing schema

Revision ID: 540209f27abd
Revises: 
Create Date: 2026-08-24 16:05:24.491578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540209f27abd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revenue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_creator_id'), 'revenue', ['creator_id'], unique=False)
    op.create_index(op.f('ix_revenue_date'), 'revenue', ['date'], unique=False)
    op.create_index(op.f('ix_revenue_id'), 'revenue', ['id'], unique=False)
    op.create_index(op.f('ix_revenue_source'), 'revenue', ['source'], unique=False)
    op.create_table('sponsorship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=150), nullable=False),
    sa.Column('campaign_name', sa.String(length=150), nullable=False),
    sa.Column('contract_value', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsorship_brand_name'), 'sponsorship', ['brand_name'], unique=False)
    op.create_index(op.f('ix_sponsorship_creator_id'), 'sponsorship', ['creator_id'], unique=False)
    op.create_index(op.f('ix_sponsorship_id'), 'sponsorship', ['id'], unique=False)
    op.drop_constraint(op.f('uq_content_platform_external_id'), 'content', type_='unique')
    op.create_index(op.f('ix_content_external_content_id'), 'content', ['external_content_id'], unique=False)
    op.create_index(op.f('ix_content_platform'), 'content', ['platform'], unique=False)
    op.create_unique_constraint('uq_creator_external_content', 'content', ['creator_id', 'external_content_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_creator_external_content', 'content', type_='unique')
    op.drop_index(op.f('ix_content_platform'), table_name='content')
    op.drop_index(op.f('ix_content_external_content_id'), table_name='content')
    op.create_unique_constraint(op.f('uq_content_platform_external_id'), 'content', ['platform', 'external_content_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_sponsorship_id'), table_name='sponsorship')
    op.drop_index(op.f('ix_sponsorship_creator_id'), table_name='sponsorship')
    op.drop_index(op.f('ix_sponsorship_brand_name'), table_name='sponsorship')
    op.drop_table('sponsorship')
    op.drop_index(op.f('ix_revenue_source'), table_name='revenue')
    op.drop_index(op.f('ix_revenue_id'), table_name='revenue')
    op.drop_index(op.f('ix_revenue_date'), table_name='revenue')
    op.drop_index(op.f('ix_revenue_creator_id'), table_name='revenue')
    op.drop_table('revenue')
    # ### end Alembic commands ###
