"""add content external content id index

Revision ID: 18bb2b761651
Revises: 4adf27b62789
Create Date: 2026-08-24 09:28:16.216162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18bb2b761651'
down_revision: Union[str, Sequence[str], None] = '4adf27b62789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_content_external_content_id'), 'content', ['external_content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_external_content_id'), table_name='content')
    # ### end Alembic commands ###
