"""initial schema

Revision ID: 650681d07d98
Revises: 
Create Date: 2026-09-07 09:10:26.598624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '650681d07d98'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('age_group', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('device', sa.String(length=30), nullable=True),
    sa.Column('active_hour', sa.Integer(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audience_creator_id'), 'audience', ['creator_id'], unique=False)
    op.create_index(op.f('ix_audience_id'), 'audience', ['id'], unique=False)
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('external_content_id', sa.String(length=150), nullable=True),
    sa.Column('content_title', sa.String(length=255), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('watch_time', sa.Integer(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_creator_id'), 'content', ['creator_id'], unique=False)
    op.create_index(op.f('ix_content_external_content_id'), 'content', ['external_content_id'], unique=False)
    op.create_index(op.f('ix_content_id'), 'content', ['id'], unique=False)
    op.create_table('growth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('new_followers', sa.Integer(), nullable=False),
    sa.Column('unfollows', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_creator_id'), 'growth', ['creator_id'], unique=False)
    op.create_index(op.f('ix_growth_id'), 'growth', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_creator_id'), 'notifications', ['creator_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('revenue_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_records_creator_id'), 'revenue_records', ['creator_id'], unique=False)
    op.create_index(op.f('ix_revenue_records_id'), 'revenue_records', ['id'], unique=False)
    op.create_table('sponsorships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=150), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('deal_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsorships_creator_id'), 'sponsorships', ['creator_id'], unique=False)
    op.create_index(op.f('ix_sponsorships_id'), 'sponsorships', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CREATOR', 'AGENCY', 'MARKETING_TEAM', 'ADMINISTRATOR', name='userrole'), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sponsorships_id'), table_name='sponsorships')
    op.drop_index(op.f('ix_sponsorships_creator_id'), table_name='sponsorships')
    op.drop_table('sponsorships')
    op.drop_index(op.f('ix_revenue_records_id'), table_name='revenue_records')
    op.drop_index(op.f('ix_revenue_records_creator_id'), table_name='revenue_records')
    op.drop_table('revenue_records')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_creator_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_growth_id'), table_name='growth')
    op.drop_index(op.f('ix_growth_creator_id'), table_name='growth')
    op.drop_table('growth')
    op.drop_index(op.f('ix_content_id'), table_name='content')
    op.drop_index(op.f('ix_content_external_content_id'), table_name='content')
    op.drop_index(op.f('ix_content_creator_id'), table_name='content')
    op.drop_table('content')
    op.drop_index(op.f('ix_audience_id'), table_name='audience')
    op.drop_index(op.f('ix_audience_creator_id'), table_name='audience')
    op.drop_table('audience')
    # ### end Alembic commands ###
