"""allow null views/shares/reach for platforms with unavailable metrics

Revision ID: 5981b079a297
Revises: bb7a2609ea3b
Create Date: 2026-08-30 16:46:00.693402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5981b079a297'
down_revision: Union[str, Sequence[str], None] = 'bb7a2609ea3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
