"""add sponsorships table and user creator_id column

Revision ID: 5baac30804b7
Revises: 
Create Date: 2026-08-21 16:22:46.802258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5baac30804b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_platform_external_id'), table_name='content')
    op.create_index(op.f('ix_content_external_content_id'), 'content', ['external_content_id'], unique=False)
    op.add_column('users', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_creator_id'), 'users', ['creator_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_creator_id'), table_name='users')
    op.drop_column('users', 'creator_id')
    op.drop_index(op.f('ix_content_external_content_id'), table_name='content')
    op.create_index(op.f('idx_platform_external_id'), 'content', ['platform', 'external_content_id'], unique=False)
    # ### end Alembic commands ###
