"""initial schema: users, content, audience, revenue, sponsorships

Revision ID: d9f3851149b0
Revises: 
Create Date: 2026-09-02 11:27:04.167078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types


# revision identifiers, used by Alembic.
revision: str = 'd9f3851149b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('creator', 'admin', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audience_demographics',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('creator_id', app.db.types.GUID(), nullable=False),
    sa.Column('platform', sa.Enum('youtube', 'instagram', 'tiktok', name='platform'), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('age_group', sa.Enum('age_13_17', 'age_18_24', 'age_25_34', 'age_35_44', 'age_45_54', 'age_55_plus', name='agegroup'), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender'), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audience_demographics_creator_id'), 'audience_demographics', ['creator_id'], unique=False)
    op.create_table('audience_growth',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('creator_id', app.db.types.GUID(), nullable=False),
    sa.Column('platform', sa.Enum('youtube', 'instagram', 'tiktok', name='platform'), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audience_growth_creator_id'), 'audience_growth', ['creator_id'], unique=False)
    op.create_table('content',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('creator_id', app.db.types.GUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.Enum('youtube', 'instagram', 'tiktok', name='platform'), nullable=False),
    sa.Column('content_type', sa.Enum('video', 'short', 'post', 'reel', 'story', name='contenttype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('publish_date', sa.DateTime(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_creator_id'), 'content', ['creator_id'], unique=False)
    op.create_index(op.f('ix_content_external_id'), 'content', ['external_id'], unique=False)
    op.create_table('revenue',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('creator_id', app.db.types.GUID(), nullable=False),
    sa.Column('source', sa.Enum('youtube', 'instagram', 'tiktok', name='platform'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('revenue_type', sa.Enum('ad_revenue', 'sponsorship', 'affiliate', 'merchandise', 'membership', 'other', name='revenuetype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'received', 'cancelled', name='revenuestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_creator_id'), 'revenue', ['creator_id'], unique=False)
    op.create_table('sponsorships',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('creator_id', app.db.types.GUID(), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=False),
    sa.Column('campaign', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'completed', 'cancelled', name='sponsorshipstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsorships_creator_id'), 'sponsorships', ['creator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sponsorships_creator_id'), table_name='sponsorships')
    op.drop_table('sponsorships')
    op.drop_index(op.f('ix_revenue_creator_id'), table_name='revenue')
    op.drop_table('revenue')
    op.drop_index(op.f('ix_content_external_id'), table_name='content')
    op.drop_index(op.f('ix_content_creator_id'), table_name='content')
    op.drop_table('content')
    op.drop_index(op.f('ix_audience_growth_creator_id'), table_name='audience_growth')
    op.drop_table('audience_growth')
    op.drop_index(op.f('ix_audience_demographics_creator_id'), table_name='audience_demographics')
    op.drop_table('audience_demographics')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
