"""social_connections

Revision ID: 57dbce131767
Revises: 0003_user_profile_fields
Create Date: 2026-08-09 15:07:57.610231
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '57dbce131767'
down_revision: Union[str, Sequence[str], None] = '0003_user_profile_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_user_id', sa.String(length=255), nullable=True),
    sa.Column('platform_username', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='not_configured', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform', name='uix_user_platform')
    )
    op.create_index(op.f('ix_social_connections_id'), 'social_connections', ['id'], unique=False)
    op.create_index(op.f('ix_social_connections_platform'), 'social_connections', ['platform'], unique=False)
    op.create_index(op.f('ix_social_connections_user_id'), 'social_connections', ['user_id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_social_connections_user_id'), table_name='social_connections')
    op.drop_index(op.f('ix_social_connections_platform'), table_name='social_connections')
    op.drop_index(op.f('ix_social_connections_id'), table_name='social_connections')
    op.drop_table('social_connections')
    # ### end Alembic commands ###
