"""Add content table

Revision ID: d19215b6cd34
Revises: 57dbce131767
Create Date: 2026-08-11 14:25:27.864000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'd19215b6cd34'
down_revision: Union[str, Sequence[str], None] = '57dbce131767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
