"""add audience and growth tables

Revision ID: ffbffb21d18c
Revises: d19215b6cd34
Create Date: 2026-08-16 17:05:37.766108
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'ffbffb21d18c'
down_revision: Union[str, Sequence[str], None] = 'd19215b6cd34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('age_group', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('active_hour', sa.Integer(), nullable=False),
    sa.Column('followers', sa.Integer(), server_default='0', nullable=False),
    sa.Column('impressions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reach', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audience_creator_id'), 'audience', ['creator_id'], unique=False)
    op.create_index(op.f('ix_audience_id'), 'audience', ['id'], unique=False)
    op.create_table('growth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('followers', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reach', sa.Integer(), server_default='0', nullable=False),
    sa.Column('engagement_rate', sa.Float(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_creator_id'), 'growth', ['creator_id'], unique=False)
    op.create_index(op.f('ix_growth_id'), 'growth', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_growth_id'), table_name='growth')
    op.drop_index(op.f('ix_growth_creator_id'), table_name='growth')
    op.drop_table('growth')
    op.drop_index(op.f('ix_audience_id'), table_name='audience')
    op.drop_index(op.f('ix_audience_creator_id'), table_name='audience')
    op.drop_table('audience')
    # ### end Alembic commands ###
