import React,{useEffect,useState} from "react"; import {Routes,Route,Link} from "react-router-dom"; import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,BarChart,Bar} from "recharts"; import {getSummary,getPlatformComparison,getTopContent,getEngagementChart,getFollowerChart,getAudience,getRevenue} from "./api";
const nav=[["/","Dashboard"],["/content","Content Analytics"],["/audience","Audience Analytics"],["/growth","Growth & Trends"],["/revenue","Revenue"],["/sponsorships","Sponsorships"],["/notifications","Notifications"],["/reports","Reports"],["/profile","Profile / Settings"]];
function Layout({children}){return <div className="min-h-screen flex"><aside className="w-64 bg-slate-900 text-white p-5 hidden md:block"><h1 className="text-2xl font-bold mb-8">CreatorIQ</h1>{nav.map(([p,n])=><Link key={p} to={p} className="block rounded px-3 py-2 mb-1 hover:bg-slate-700">{n}</Link>)}</aside><main className="flex-1 p-5 md:p-8">{children}</main></div>}
function Card({title,value}){return <div className="bg-white rounded-xl p-5 shadow-sm border"><div className="text-slate-500 text-sm">{title}</div><div className="text-2xl font-bold mt-2">{value??"—"}</div></div>}
function Dashboard(){const [s,setS]=useState(null),[pc,setPc]=useState({}),[top,setTop]=useState([]),[fc,setFc]=useState({labels:[],values:[]}),[ec,setEc]=useState({labels:[],values:[]}),[err,setErr]=useState(""),[platform,setPlatform]=useState("");
useEffect(()=>{const q=platform?`?platform=${encodeURIComponent(platform)}`:""; Promise.all([getSummary(platform),getPlatformComparison(),getTopContent(platform),getFollowerChart(),getEngagementChart(platform)]).then(([a,b,c,d,e])=>{setS(a);setPc(b);setTop(c);setFc(d);setEc(e)}).catch(x=>setErr(x.message))},[platform]);
const followers=fc.labels.map((x,i)=>({date:x,value:fc.values[i]})); const engagement=ec.labels.map((x,i)=>({date:x,value:ec.values[i]}));
return <><header className="flex justify-between items-center mb-8"><div><h2 className="text-3xl font-bold">Creator Dashboard</h2><p className="text-slate-500">Live data from FastAPI and PostgreSQL</p></div><select value={platform} onChange={e=>setPlatform(e.target.value)} className="text-sm bg-white border rounded px-3 py-2">
<option value="">All Platforms</option><option>YouTube</option><option>Instagram</option><option>LinkedIn</option><option>Facebook</option><option>TikTok</option><option>X</option>
</select></header>{err&&<div className="bg-red-50 text-red-700 p-3 rounded mb-4">Backend error: {err}</div>}<div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6"><Card title="Total Views" value={s?.total_views?.toLocaleString()}/><Card title="Total Reach" value={s?.total_reach?.toLocaleString()}/><Card title="Followers" value={s?.total_followers?.toLocaleString()}/><Card title="Avg Engagement" value={s?`${s.average_engagement_rate}%`:"—"}/></div><div className="grid lg:grid-cols-2 gap-5"><section className="bg-white rounded-xl p-5 shadow-sm border"><h3 className="font-semibold mb-4">Follower Growth</h3><div className="h-64"><ResponsiveContainer><LineChart data={followers}><XAxis dataKey="date"/><YAxis/><Tooltip/><Line type="monotone" dataKey="value"/></LineChart></ResponsiveContainer></div></section><section className="bg-white rounded-xl p-5 shadow-sm border"><h3 className="font-semibold mb-4">Engagement Rate</h3><div className="h-64"><ResponsiveContainer><LineChart data={engagement}><XAxis dataKey="date"/><YAxis/><Tooltip/><Line type="monotone" dataKey="value"/></LineChart></ResponsiveContainer></div></section></div><section className="bg-white rounded-xl p-5 shadow-sm border mt-5"><h3 className="font-semibold mb-4">Platform Comparison</h3><div className="h-72"><ResponsiveContainer><BarChart data={Object.entries(pc).map(([platform,v])=>({platform,...v}))}><XAxis dataKey="platform"/><YAxis/><Tooltip/><Bar dataKey="views"/></BarChart></ResponsiveContainer></div></section><section className="bg-white rounded-xl p-5 shadow-sm border mt-5"><h3 className="font-semibold mb-4">Top Content</h3><div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left border-b"><th className="p-2">Title</th><th>Platform</th><th>Views</th><th>Reach</th><th>Engagement</th></tr></thead><tbody>{top.map(x=><tr key={x.content_id} className="border-b"><td className="p-2">{x.content_title}</td><td>{x.platform}</td><td>{x.views.toLocaleString()}</td><td>{x.reach.toLocaleString()}</td><td>{x.engagement_rate}%</td></tr>)}</tbody></table></div></section></>}
function Simple({title,children}){return <><h2 className="text-3xl font-bold mb-6">{title}</h2><div className="bg-white border rounded-xl p-6 shadow-sm">{children}</div></>}
function Audience(){const [a,setA]=useState(null);useEffect(()=>{getAudience().then(setA).catch(()=>{})},[]);return <Simple title="Audience Analytics"><div className="grid md:grid-cols-3 gap-4"><Card title="Followers" value={a?.total_followers?.toLocaleString()}/><Card title="Reach" value={a?.total_reach?.toLocaleString()}/><Card title="Impressions" value={a?.total_impressions?.toLocaleString()}/></div><pre className="mt-5 bg-slate-50 p-4 rounded overflow-auto">{JSON.stringify(a,null,2)}</pre></Simple>}
function Revenue(){const [r,setR]=useState(null);useEffect(()=>{getRevenue().then(setR).catch(()=>{})},[]);return <Simple title="Revenue Analytics"><Card title="Total Revenue" value={r?`₹${r.total_revenue.toLocaleString()}`:"—"}/><pre className="mt-5 bg-slate-50 p-4 rounded">{JSON.stringify(r?.revenue_by_source,null,2)}</pre></Simple>}
function ContentPage(){const [rows,setRows]=useState([]);useEffect(()=>{import("./api").then(({api})=>api.get("/content").then(r=>setRows(r.data)))},[]);return <Simple title="Content Analytics"><div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Title</th><th>Platform</th><th>Views</th><th>Likes</th><th>Comments</th><th>Reach</th></tr></thead><tbody>{rows.map(x=><tr className="border-b" key={x.id}><td className="p-2">{x.content_title}</td><td>{x.platform}</td><td>{x.views.toLocaleString()}</td><td>{x.likes.toLocaleString()}</td><td>{x.comments.toLocaleString()}</td><td>{x.reach.toLocaleString()}</td></tr>)}</tbody></table></div></Simple>}
function Growth(){const [g,setG]=useState({labels:[],values:[]});useEffect(()=>{getFollowerChart().then(setG).catch(()=>{})},[]);return <Simple title="Growth & Trends"><div className="h-80"><ResponsiveContainer><LineChart data={g.labels.map((date,i)=>({date,followers:g.values[i]}))}><XAxis dataKey="date"/><YAxis/><Tooltip/><Line type="monotone" dataKey="followers"/></LineChart></ResponsiveContainer></div></Simple>}
function Reports(){return <Simple title="Reports & Export"><p className="text-slate-600 mb-4">Generate reports from current PostgreSQL-backed analytics.</p><div className="flex gap-3"><a className="px-4 py-2 rounded bg-slate-900 text-white" href={(import.meta.env.VITE_API_URL||"http://127.0.0.1:8000")+"/reports/pdf"}>Download PDF</a><a className="px-4 py-2 rounded bg-slate-200" href={(import.meta.env.VITE_API_URL||"http://127.0.0.1:8000")+"/reports/excel"}>Download Excel</a></div></Simple>}
function Notifications(){const [n,setN]=useState([]);useEffect(()=>{import("./api").then(({api})=>api.get("/notifications").then(r=>setN(r.data)))},[]);return <Simple title="Notifications"><div className="space-y-3">{n.map(x=><div key={x.id} className="p-3 rounded border"><b>{x.title}</b><p className="text-slate-600">{x.message}</p></div>)}{!n.length&&<p>No notifications yet. Use POST /notifications/generate.</p>}</div></Simple>}
export default function App(){return <Layout><Routes><Route path="/" element={<Dashboard/>}/><Route path="/audience" element={<Audience/>}/><Route path="/revenue" element={<Revenue/>}/><Route path="/content" element={<ContentPage/>}/><Route path="/growth" element={<Growth/>}/><Route path="/reports" element={<Reports/>}/><Route path="/notifications" element={<Notifications/>}/>
{nav.slice(1).filter(([p])=>!["/audience","/revenue","/content","/growth","/reports","/notifications"].includes(p)).map(([p,n])=><Route key={p} path={p} element={<Simple title={n}>Use the existing CreatorIQ FastAPI APIs from this module.</Simple>}/>)}</Routes></Layout>}
